### ISSUE TITLE
Добавить возможность удалять аккаунт 

### ISSUE THREAD

**Issue by Millniker** [Vinnichenko-Ivan/sport#3]
Необходимо добавить эндпоинт для полного удаления аккаунта для тестирования регистрации, чтобы не регистрировать много новых почт. На продакшн кнопка не пойдет

**Comment by Vinnichenko-Ivan** [comment]
Ок, метод будет защищен через X-Token

**Comment by Vinnichenko-Ivan** [comment]
Изменено. Будет метод подтверждения, так как удаление аккаунта сделать тяжелее.
